### ISSUE TITLE
Zone bug!

### ISSUE THREAD

**Issue by Dylen67** [Jonathan57500/aion-lightning-2.7#14]
Hi

Zone bug  : 

2018-09-08 11:20:37,325 WARN  [main] com.aionemu.gameserver.world.zone.ZoneService [ZoneService.java:82] Can't instantiate zone handler CORE_400010000
java.nio.BufferUnderflowException: null
	at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:235) ~[na:1.6.0_45]
	at java.nio.ByteBuffer.get(ByteBuffer.java:675) ~[na:1.6.0_45]
	at com.aionemu.gameserver.geoEngine.GeoWorldLoader.loadMeshs(GeoWorldLoader.java:67) ~[AL-Game.jar:na]
	at zone.AbyssCore.<init>(AbyssCore.java from JavaSourceFromFile:54) ~[na:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.6.0_45]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39) ~[na:1.6.0_45]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27) ~[na:1.6.0_45]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513) ~[na:1.6.0_45]
	at java.lang.Class.newInstance0(Class.java:357) ~[na:1.6.0_45]
	at java.lang.Class.newInstance(Class.java:310) ~[na:1.6.0_45]
	at com.aionemu.gameserver.world.zone.ZoneService.getNewZoneHandler(ZoneService.java:76) [AL-Game.jar:na]
	at com.aionemu.gameserver.world.zone.ZoneService.getZoneInstancesByWorldId(ZoneService.java:180) [AL-Game.jar:na]
	at com.aionemu.gameserver.world.WorldMapInstance.<init>(WorldMapInstance.java:122) [AL-Game.jar:na]
	at com.aionemu.gameserver.world.WorldMap3DInstance.<init>(WorldMap3DInstance.java:32) [AL-Game.jar:na]
	at com.aionemu.gameserver.world.WorldMapInstanceFactory.createWorldMapInstance(WorldMapInstanceFactory.java:35) [AL-Game.jar:na]
	at com.aionemu.gameserver.world.WorldMap.<init>(WorldMap.java:58) [AL-Game.jar:na]
	at com.aionemu.gameserver.world.World.<init>(World.java:95) [AL-Game.jar:na]
	at com.aionemu.gameserver.world.World.<init>(World.java:53) [AL-Game.jar:na]
	at com.aionemu.gameserver.world.World$SingletonHolder.<clinit>(World.java:481) [AL-Game.jar:na]
	at com.aionemu.gameserver.world.World.getInstance(World.java:100) [AL-Game.jar:na]
	at com.aionemu.gameserver.GameServer.main(GameServer.java:174) [AL-Game.jar:na]

**Comment by zdbear** [comment]
sorry for offtop, but
Jonathan, i need to contact to you. i haven't found the way to send a message in private, but im interested in your 2.7 build and have dumb questions about launching specifically your server and such stuff.
if you can help, send a message on mazafaka2004@gmail.com .
i'll be so grateful if you help.

**Comment by Jonathan57500** [comment]
Hi,
There is nothing we can do here as this function can't be improved (or btw I didn't find how to fix it).
