### ISSUE TITLE
Everything going fine , but only this error message

### ISSUE THREAD

**Issue by FliesQQ** [Jonathan57500/aion-lightning-2.7#60]
Can't instantiate zone handler CORE_400010000

java.nio.BufferUnderflowException: null
        at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:235) ~[na:1.6.0_30]
        at java.nio.ByteBuffer.get(ByteBuffer.java:675) ~[na:1.6.0_30]
        at com.aionemu.gameserver.geoEngine.GeoWorldLoader.loadMeshs(GeoWorldLoader.java:67) ~[AL-Game.jar:na]
        at zone.AbyssCore.<init>(AbyssCore.java from JavaSourceFromFile:54) ~[na:na]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.6.0_30]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39) ~[na:1.6.0_30]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27) ~[na:1.6.0_30]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:513) ~[na:1.6.0_30]
        at java.lang.Class.newInstance0(Class.java:355) ~[na:1.6.0_30]
        at java.lang.Class.newInstance(Class.java:308) ~[na:1.6.0_30]
        at com.aionemu.gameserver.world.zone.ZoneService.getNewZoneHandler(ZoneService.java:76) [AL-Game.jar:na]
        at com.aionemu.gameserver.world.zone.ZoneService.getZoneInstancesByWorldId(ZoneService.java:180) [AL-Game.jar:na]
        at com.aionemu.gameserver.world.WorldMapInstance.<init>(WorldMapInstance.java:122) [AL-Game.jar:na]
        at com.aionemu.gameserver.world.WorldMap3DInstance.<init>(WorldMap3DInstance.java:32) [AL-Game.jar:na]
        at com.aionemu.gameserver.world.WorldMapInstanceFactory.createWorldMapInstance(WorldMapInstanceFactory.java:35) [AL-Game.jar:na]
        at com.aionemu.gameserver.world.WorldMap.<init>(WorldMap.java:58) [AL-Game.jar:na]
        at com.aionemu.gameserver.world.World.<init>(World.java:95) [AL-Game.jar:na]
        at com.aionemu.gameserver.world.World.<init>(World.java:53) [AL-Game.jar:na]
        at com.aionemu.gameserver.world.World$SingletonHolder.<clinit>(World.java:481) [AL-Game.jar:na]
        at com.aionemu.gameserver.world.World.getInstance(World.java:100) [AL-Game.jar:na]
        at com.aionemu.gameserver.GameServer.main(GameServer.java:175) [AL-Game.jar:na]

**Comment by Jonathan57500** [comment]
Hi, this is not an error, only a warning, this is because geodata canno't be fully loaded into the map Abyss (a known problem with the geomap system)

**Comment by FliesQQ** [comment]
And another bugs , that dialogid 60 is not functional, so instance entry of beshmundir Temple can't going in .

**Comment by Jonathan57500** [comment]
This is because the Normal and High ways are not implemented, there is only one way currently

**Comment by yonghwanil** [comment]
The cause of this problem is file 'AL-Game/data/scripts/system/handlers/zone/AbyssCore.java'.

i'm delete this file then not happen error.

but, i don't know any side effect.

if you know work of this file, please let me know.

thank you.

**Comment by Jonathan57500** [comment]
Please do not remove files as you don't know what can be the consequences with geodata on this map abd what's happening when you enable geodata

**Comment by yonghwanil** [comment]
Thank you for your response.

Thank you very much !!

**Comment by FliesQQ** [comment]
And another question，How can I enter this instance with no using of moveto command? Normal way is impossible .
